# Use the official Nginx image as the base image
FROM nginx:stable

# Copy the custom HTML file to the Nginx web directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80
