apiVersion: v1
kind: Service
metadata:
  name: simple-web-app-service
spec:
  type: NodePort
  selector:
    app: simple-web-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001 # Port to access the service externally
